/* 공개 자료 확인: 2026-10-01. 학과 정보 변경 시 이 파일을 수정하세요. */
const BASE = 'https://icms.pknu.ac.kr/ps1/';
const DEPARTMENT = {
  faculty: [
    {name:'김은정',role:'교수',area:'사회복지정책 · 사회복지행정 · 지역복지서비스',email:'ejkim@pknu.ac.kr',phone:'051-629-5459',id:'19404141',photo:'assets/professor-1.jpg'},
    {name:'오영삼',role:'교수 · 전공주임',area:'사회복지실천 · 사회복지실천기술 · 노인복지',email:'pknu503@gmail.com',phone:'051-629-5463',id:'19404142',photo:'assets/professor-2.jpg'},
    {name:'허원빈',role:'교수 · 일반대학원 학과주임',area:'사회복지실천 · 아동복지 · 중독과 정신건강 · 질적연구방법',email:'wonbinonebin@pknu.ac.kr',phone:'051-629-5464',id:'19404143',photo:'assets/professor-3.png'},
    {name:'노법래',role:'교수 · 글로벌정책대학원 학과주임',area:'복지국가 및 지역비교 · 사회통계(빅데이터)',email:'profroh@pknu.ac.kr',phone:'051-629-5487',id:'19404144',photo:'assets/professor-4.jpg'},
    {name:'조윤호',role:'교수',area:'아동청소년복지 · 국제개발협력 · 지역사회개발',email:'ireenee2u@pknu.ac.kr',phone:'051-629-5488',id:'19406054',photo:'assets/professor-5.png'}
  ],
  achievements: [
    {title:'대연3동과 이어가는 지역 복지 협력',period:'2026',tag:'지역사회',desc:'공식 전공성과 게시판에 소개된 대연3동 복지공감 네트워크 협약 소식. 지역사회와 학과의 연결을 만나보세요.'},
    {title:'학생이 제안하는 새로운 배움',period:'2025',tag:'학생 성과',desc:'Credi-T 학생주도형 비교과 아이디어 공모전에서 전공 학생들의 수상 소식이 소개되었습니다.'},
    {title:'현장 경험으로 만들어낸 성과',period:'2025',tag:'현장·진로',desc:'미래내일 일경험 우수사례 공모전의 고용노동부 장관상 수상 소식이 공식 전공성과 게시판에 소개되었습니다.'},
    {title:'디지털 금융의 포용을 고민하다',period:'2025',tag:'정책 아이디어',desc:'디지털 금융포용 정책 아이디어 공모전에서 우수상을 받은 소식이 소개되었습니다.'},
    {title:'보건복지의 이야기를 널리 전하다',period:'2025',tag:'콘텐츠',desc:'슬라이드ON: 보건복지 ON AIR 공모전에서 우수작으로 선정된 소식이 소개되었습니다.'}
  ],
  videos: [
    {id:'u6TVBS7ZpNY',title:'내 다솜 모임을 소개합니다',desc:'추억, 행복, 낭만을 담은 다솜 소개 영상',label:'DASOM / INTRO',image:'assets/dasom-u6TVBS7ZpNY.jpg'},
    {id:'ALtH_vsgxqg',title:'우리들의 학창시절, 다솜중학교',desc:'2026년 제2회 · 통합 17회 다솜모임',label:'DASOM / 2026',image:'assets/dasom-ALtH_vsgxqg.jpg'},
    {id:'GXDGZ-mMJQU',title:'봄날에 다솜 급식데이',desc:'2026년 제1회 · 통합 16회 다솜모임',label:'DASOM / SPRING',image:'assets/dasom-GXDGZ-mMJQU.jpg'},
    {id:'UoWY3yV3fbw',title:'예비 신입생 친밀감 형성 프로그램',desc:'2026년 사회복지학전공 학부 1학년 프로그램',label:'WELCOME / 2026'},
    {id:'p7IEfpmLxyY',title:'학위수여식, 그대에게 띄우는 편지',desc:'2026년 사회복지학전공 학위수여식 2부',label:'GRADUATION / 2026'},
    {id:'AROBINTOI04',title:'학위수여식, 낭만에 대하여',desc:'2026년 사회복지학전공 학위수여식 1부',label:'GRADUATION / 2026'}
  ],
  resources: [
    {name:'복지로',desc:'복지서비스를 찾아보고 신청 안내를 확인하는 출발점',tag:'복지서비스',url:'https://www.bokjiro.go.kr/ssis-tbu/'},
    {name:'보건복지부',desc:'복지정책, 보도자료, 법령과 사업 안내',tag:'정책·제도',url:'https://www.mohw.go.kr/'},
    {name:'한국사회복지사협회',desc:'사회복지사 관련 자격·교육·전문직 정보',tag:'자격·진로',url:'https://www.welfare.net/'},
    {name:'VMS 사회복지자원봉사인증관리',desc:'사회복지 자원봉사 활동과 인증 정보 확인',tag:'자원봉사',url:'https://www.vms.or.kr/'},
    {name:'KOSIS 국가통계포털',desc:'인구, 가구, 복지 등 사회 현상을 이해하는 국가 통계',tag:'통계·데이터',url:'https://kosis.kr/'},
    {name:'한국보건사회연구원',desc:'보건·복지 정책 연구와 보고서 탐색',tag:'연구·보고서',url:'https://www.kihasa.re.kr/'}
  ]
};
const external = (url,text) => `<a href="${url}" target="_blank" rel="noopener noreferrer">${text}</a>`;
const source = (id,text='공식 학과 홈페이지') => `<p class="source">자료: ${external(BASE+id,text)} · 확인일 2026.10.01</p>`;
const videos = list => `<div class="video-grid">${list.map(v=>`<a class="video-card" href="https://www.youtube.com/watch?v=${v.id}" target="_blank" rel="noopener noreferrer">${v.image?`<img src="${v.image}" alt="${v.title} 영상 썸네일" loading="lazy">`:`<div class="video-art" aria-hidden="true">${v.label.split(' / ')[0]} <span>&nbsp;▷</span></div>`}<h4>${v.title}</h4><p>${v.desc} · YouTube에서 보기</p></a>`).join('')}</div>`;
const programHeader = `<div class="program-tabs"><button data-open="undergrad">학부</button><button data-open="graduate">일반대학원</button><button data-open="global">글로벌정책대학원</button></div>`;
const CONTENT = {
  programs:{title:'학부 · 대학원',html:()=>`<span class="kicker">THREE PATHS, ONE PURPOSE</span><h3>배움의 방향을 찾아보세요.</h3><p class="lead">사회복지의 첫걸음부터 연구와 정책의 전문성까지. 학부와 두 대학원 과정을 각각 만나보세요.</p>${programHeader}<div class="info-grid"><article class="info-card"><h4>학부 · 사회복지학전공</h4><p>학사 과정. 사회복지의 이론과 실천을 배우고 현장과 연결되는 배움의 길입니다.</p><div class="content-links"><button data-open="undergrad">학부 소개</button></div></article><article class="info-card"><h4>일반대학원 · 사회복지학과</h4><p>석사·박사 과정. 사회복지 현상을 탐구하고 연구의 깊이를 더하는 길입니다.</p><div class="content-links"><button data-open="graduate">일반대학원 소개</button></div></article><article class="info-card"><h4>글로벌정책대학원 · 사회복지학과</h4><p>석사 과정. 복지정책과 실천을 함께 살펴보는 전문적인 배움의 길입니다.</p><div class="content-links"><button data-open="global">글로벌정책대학원 소개</button></div></article><article class="info-card"><h4>어떤 과정이 나에게 맞을까요?</h4><p>학위 목표와 관심 분야를 먼저 살펴보세요. 모집 일정, 지원 자격, 수업 운영은 각 과정의 공식 공지에서 확인할 수 있습니다.</p><div class="content-links"><button data-open="contact">학과에 문의하기</button></div></article></div>${source('1')}`},
  undergrad:{title:'학부 · 사회복지학전공',html:()=>`<span class="kicker">UNDERGRADUATE / 학사</span><h3>사람과 사회를 이해하는<br>첫 번째 배움.</h3><p class="lead">국립부경대학교 사회복지학전공의 학부 과정입니다. 교수진의 연구 분야와 교육과정, 현장실습 안내를 함께 살펴보세요.</p>${programHeader}<div class="info-grid"><article class="info-card"><h4>이론과 실천</h4><p>정책과 행정, 실천과 실천기술, 아동·청소년과 노인복지 등 다양한 관심 분야를 탐색합니다. 구체적인 개설 교과목은 공식 교육과정을 확인하세요.</p></article><article class="info-card"><h4>복지와 기술의 연결</h4><p>공식 홈페이지에서 ‘복지ICT 마이크로전공’ 교육과정도 별도로 안내합니다. 이수 가능 여부와 요건은 해당 안내에서 확인하세요.</p></article></div><h4 class="section-label">학부생에게 필요한 안내</h4><div class="content-links">${external(BASE+'6392','교육과정')}${external(BASE+'6394','졸업요건')}${external(BASE+'6395','장학제도')}${external(BASE+'6397','사회복지현장실습')}${external(BASE+'6487','자격증')}${external(BASE+'6488','졸업 후 진로')}</div><details><summary>전공을 처음 알아보고 있어요.</summary><p>교육과정과 교수 연구 분야를 먼저 읽어보세요. 학생 활동과 다솜모임 영상에서는 전공 안에서 함께하는 모습을 만날 수 있습니다.</p></details><details><summary>현장실습과 자격증은 어디서 확인하나요?</summary><p>현장실습 공지와 자격증 안내에 연결된 최신 자료를 확인하세요. 개인별 이수 요건은 학과 사무실에 문의할 수 있습니다.</p></details>${source('6388')}`},
  graduate:{title:'일반대학원 · 사회복지학과',html:()=>`<span class="kicker">GRADUATE SCHOOL / 석사 · 박사</span><h3>질문을 연구로,<br>연구를 사회의 변화로.</h3><p class="lead">일반대학원 사회복지학과는 석사·박사 과정을 안내합니다. 관심 있는 사회복지 주제와 연구 방법을 중심으로 학업의 방향을 살펴보세요.</p>${programHeader}<div class="info-grid"><article class="info-card"><h4>연구 관심 분야 탐색</h4><p>복지정책과 지역 서비스, 사회복지실천, 아동·노인복지, 정신건강, 사회통계 등 교수진의 연구 분야에서 나의 질문을 찾아보세요.</p><div class="content-links"><button data-open="faculty">교수진 연구 분야</button></div></article><article class="info-card"><h4>학과주임 · 허원빈 교수</h4><p>사회복지실천, 아동복지, 중독과 정신건강, 질적연구방법.</p><div class="content-links">${external(BASE+'6927','교육목표·교육과정')}</div></article></div><h4 class="section-label">일반대학원 안내</h4><div class="content-links">${external(BASE+'6406','공지사항')}${external(BASE+'7048','학과소식')}${external(BASE+'7750','자주 찾는 질문')}${external(BASE+'6407','자료실')}</div><p>모집 일정, 지원 요건, 학위 취득 요건은 해당 연도의 공식 안내를 확인하세요.</p>${source('6927','일반대학원 사회복지학과 소개')}`},
  global:{title:'글로벌정책대학원 · 사회복지학과',html:()=>`<span class="kicker">GLOBAL POLICY / 석사</span><h3>복지정책과 현장을<br>함께 바라보는 배움.</h3><p class="lead">글로벌정책대학원 사회복지학과는 석사 과정을 안내합니다. 복지 현장에서 마주하는 문제를 정책과 사회의 관점으로 살펴보세요.</p>${programHeader}<div class="info-grid"><article class="info-card"><h4>과정 알아보기</h4><p>공식 학과 소개에는 교육목표, 교수진과 교육과정이 안내되어 있습니다. 학업 계획에 맞춰 자세한 내용을 확인해보세요.</p><div class="content-links">${external(BASE+'6928','교육목표·교육과정')}</div></article><article class="info-card"><h4>학과주임 · 노법래 교수</h4><p>복지국가 및 지역비교, 사회통계(빅데이터).</p><div class="content-links"><button data-open="faculty">교수 소개</button></div></article></div><h4 class="section-label">글로벌정책대학원 안내</h4><div class="content-links">${external(BASE+'7049','공지사항')}${external(BASE+'8288','학과소식')}${external(BASE+'7742','자료실')}</div><p>모집 일정, 지원 자격, 수업 시간과 학위 요건은 최신 공지 또는 학과 문의를 통해 확인하세요.</p>${source('6928','글로벌정책대학원 사회복지학과 소개')}`},
  faculty:{title:'교수 소개',html:()=>`<span class="kicker">MEET OUR FACULTY</span><h3>서로 다른 질문,<br>함께 만드는 사회복지.</h3><p class="lead">정책, 실천, 연구 방법과 지역사회. 교수진의 연구 분야를 만나보세요.</p>${DEPARTMENT.faculty.map(f=>`<article class="faculty-card"><img src="${f.photo}" alt="${f.name} 교수" loading="lazy"><div><h4>${f.name}</h4><span class="role">${f.role}</span><p>${f.area}</p><div class="faculty-contacts"><a href="mailto:${f.email}">${f.email}</a><a href="tel:${f.phone.replaceAll('-','')}">${f.phone}</a>${external(BASE+'6390?action=view&no='+f.id,'프로필 보기')}</div></div></article>`).join('')}${source('6390','공식 교수진 소개')}`},
  life:{title:'학생 활동',html:()=>`<span class="kicker">LIFE AT PKNU</span><h3>함께 배우는 날들,<br>우리의 캠퍼스 생활.</h3><p class="lead">새로운 만남부터 졸업의 순간까지. 학생들의 이야기를 학과 채널에서 만나보세요.</p><div class="content-links"><button data-open="dasom">다솜모임</button>${external('https://www.instagram.com/pknu_ps1/','인스타그램 소식')}${external(BASE+'6403','공식 전공소식')}</div>${videos(DEPARTMENT.videos.slice(3))}<h4 class="section-label">전공 안의 동아리</h4><div class="info-grid"><article class="info-card"><h4>HORA · 오라</h4><p>지도교수: 허원빈 교수</p>${external('https://www.instagram.com/hora_2024/','HORA 인스타그램')}</article><article class="info-card"><h4>클럽신화</h4><p>지도교수: 오영삼 교수</p></article><article class="info-card"><h4>theme · 띰</h4><p>공식 동아리 소개에 안내된 모임입니다.</p></article><article class="info-card"><h4>더 많은 학생 소식</h4><p>동아리의 최신 활동과 참여 안내는 공식 동아리 소개 및 학과 채널에서 확인하세요.</p>${external(BASE+'6404','공식 동아리 안내')}</article></div>${source('6404','공식 동아리 안내')}<p class="source">영상: ${external('https://www.youtube.com/@ps1pknu','학과 YouTube')} · 소식: ${external('https://www.instagram.com/pknu_ps1/','학과 Instagram')}</p>`},
  achievements:{title:'학과 성과',html:()=>`<span class="kicker">MAKING AN IMPACT</span><h3>배움을 넘어,<br>사회와 만나는 성과.</h3><p class="lead">공식 전공성과 게시판에서 확인한 수상과 협력 소식을 모았습니다.</p>${DEPARTMENT.achievements.map((n,i)=>`<article class="info-card" style="margin-top:15px"><span class="kicker">${String(i+1).padStart(2,'0')} / ${n.period} / ${n.tag}</span><h4>${n.title}</h4><p>${n.desc}</p>${external(BASE+'6856','공식 성과 게시판에서 확인')}</article>`).join('')}${source('6856','공식 전공성과 게시판')}`},
  dasom:{title:'다솜모임',html:()=>`<span class="kicker">DASOM / OUR SHARED MOMENTS</span><h3>추억, 행복, 낭만.<br>다솜으로 이어지는 우리.</h3><div class="dasom-hero"><strong>같이 만든 순간이<br>우리의 이야기가 됩니다.</strong><p>소개 영상과 모임 기록으로 만나는 다솜.</p></div><p class="lead">다솜모임은 학과 유튜브에서 회차별 영상으로 만나볼 수 있습니다. 급식데이, 다솜중학교, 크리스마스 파티처럼 각 모임의 주제를 담아 함께한 시간을 기록합니다.</p><h4 class="section-label">영상에서 만나는 다솜의 특성</h4><div class="info-grid"><article class="info-card"><h4>주제가 있는 만남</h4><p>‘봄날에 다솜 급식데이’와 ‘우리들의 학창시절 다솜중학교’처럼 일상과 추억을 담은 모임의 주제를 볼 수 있습니다.</p></article><article class="info-card"><h4>함께 쌓이는 기록</h4><p>2026년 제1회는 통합 16회, 제2회는 통합 17회로 소개됩니다. 회차를 이어가며 모임의 순간을 영상으로 남깁니다.</p></article></div><p>‘추억, 행복, 낭만’은 다솜 소개 영상 제목에서 가져온 표현입니다. 아래 영상으로 모임의 분위기를 직접 만나보세요.</p>${videos(DEPARTMENT.videos.slice(0,3))}<div class="content-links">${external('https://www.youtube.com/@ps1pknu','학과 채널 전체 보기')}<button data-open="contact">참여 안내 문의</button></div><p class="source">자료: ${external('https://www.youtube.com/watch?v=u6TVBS7ZpNY','다솜 소개 영상')} · ${external('https://www.youtube.com/watch?v=ALtH_vsgxqg','다솜중학교')} · ${external('https://www.youtube.com/watch?v=GXDGZ-mMJQU','급식데이')}<br>소개는 공개 영상 제목과 회차 정보를 바탕으로 정리했습니다. 참여 대상과 일정은 학과 채널 또는 사무실에서 확인하세요.</p>`},
  resources:{title:'사회복지 정보',html:()=>`<span class="kicker">SOCIAL WELFARE / RESOURCE DESK</span><h3>배움과 실천에 필요한<br>정보를 한곳에서.</h3><p class="lead">복지서비스와 정책부터 자격, 봉사, 연구 자료까지. 필요한 정보의 공식 출처로 연결합니다.</p>${DEPARTMENT.resources.map(r=>`<a class="resource-link" href="${r.url}" target="_blank" rel="noopener noreferrer"><div><strong>${r.name}</strong><p>${r.desc}</p></div><span>${r.tag}</span></a>`).join('')}<h4 class="section-label">전공 생활에 필요한 자료</h4><div class="content-links">${external(BASE+'6397','현장실습 공지')}${external(BASE+'6487','자격증 안내')}${external(BASE+'6400','채용공고')}${external(BASE+'6399','학과 자료실')}${external('https://pknu503.github.io/home503/','SW Research')}</div><details><summary>정책과 사회복지 이슈를 공부하려면?</summary><p>보건복지부에서 정책과 보도자료를, 한국보건사회연구원에서 관련 연구 보고서를, KOSIS에서 통계 자료를 함께 살펴보세요.</p></details><details><summary>실습과 자격 준비는 어디서 시작하나요?</summary><p>학과 현장실습 공지와 자격증 안내를 먼저 확인하고, 한국사회복지사협회의 최신 정보를 함께 참고하세요.</p></details><p class="source">각 기관의 공식 페이지로 이동합니다. 신청 요건, 일정과 제도 내용은 연결된 기관의 최신 안내를 확인하세요.</p>`},
  contact:{title:'학과 문의',html:()=>`<span class="kicker">COME SAY HELLO</span><h3>부경의 사회복지,<br>더 궁금한가요?</h3><div class="info-card"><h4>사회복지학전공 사무실</h4><p>부산광역시 남구 용소로 45<br>국립부경대학교 대연캠퍼스<br>인문사회경영관 C25 · 724호<br>우편번호 48513</p><div class="content-links"><a href="tel:0516295450">051-629-5450</a><a href="mailto:pksw5450@pknu.ac.kr">pksw5450@pknu.ac.kr</a></div></div><p>입학, 학부·대학원 과정, 실습과 전공 활동에 관한 자세한 안내는 학과 사무실 또는 공식 홈페이지를 이용해주세요.</p><div class="content-links">${external(BASE+'1','공식 홈페이지')}${external('https://www.youtube.com/@ps1pknu','YouTube')}${external('https://www.instagram.com/pknu_ps1/','Instagram')}</div>${source('1')}`},
  sources:{title:'자료 출처',html:()=>`<span class="kicker">SOURCES / 2026.10.01</span><h3>소개 자료의 출처</h3><p>학과 고유 정보는 공식 홈페이지와 학과 유튜브의 공개 자료를 기준으로 정리했습니다. 세부 교육과정과 최신 운영 안내는 원문에서 확인할 수 있습니다.</p><ul class="bullet-list"><li>${external(BASE+'1','국립부경대학교 사회복지학전공 공식 홈페이지')}</li><li>${external(BASE+'6390','교수진 소개')}</li><li>${external(BASE+'6927','일반대학원 학과 소개')}</li><li>${external(BASE+'6928','글로벌정책대학원 학과 소개')}</li><li>${external(BASE+'6856','전공성과 게시판')}</li><li>${external(BASE+'6404','동아리 소개')}</li><li>${external('https://www.youtube.com/@ps1pknu','학과 유튜브: 다솜·학생 활동 영상')}</li><li>${external('https://www.instagram.com/pknu_ps1/','학과 인스타그램: 추가 학생 활동 소식')}</li></ul><p>이 사이트는 학과를 소개하기 위해 제작한 별도 소개 사이트입니다. 공식 공지와 학사 안내는 학과 공식 홈페이지를 확인해주세요.</p>`}
};

